[technote]
id = "DMTN-334"
series_id = "DMTN"
canonical_url = "https://dmtn-334.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-334"
github_default_branch = "main"
date_created = 2026-01-28T10:26:39Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Gabriele"
name.family = "Mainetti"
internal_id = "mainettig"
orcid = "https://orcid.org/0000-0003-2384-2377"
[[technote.authors.affiliations]]
name = "CNRS/IN2P3, CC-IN2P3"
internal_id = "IN2P3-CC"
address = "Villeurbanne"
